version: "3.7"

services:
  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    volumes:
      - yaikibardb-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yaikibardb

volumes:
  yaikibardb-mysql: